### ISSUE TITLE
Pyroscope libraries resulting in segmentation fault

### ISSUE THREAD

**Issue by sentient-glare** [pyroscope-io/pyroscope-dotnet#20]
Following the instructions for the [dotnet beta integration](https://pyroscope.io/docs/dotnet-beta/). I am trying to profile an ASPNET application with Pyroscope.

Dockerfile below - this is largely copied from a Microsoft example. When I build and run this, the container exits with a `139` code (seg fault).

Things I've tried:
- Downgrading Pyroscope libraries from `0.7.2` to `0.7.0`
- Using Debian and Ubuntu images instead of Alpine
- Messing around with the `libc6-compat` library instead of `gcompat`

```
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.16 AS build
WORKDIR /sln

# Copy project file and restore
COPY "TestApp.Api.csproj" "."
RUN dotnet restore TestApp.Api.csproj

# Copy the actual source code
COPY "." "."

# Build and publish the app
RUN dotnet publish "TestApp.Api.csproj" -c Release -o /app/publish --self-contained false --no-restore

#FINAL image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16
WORKDIR /app
COPY --from=build /app/publish .

# Set up Pyroscope profiling
RUN apk update && apk add gcompat
RUN wget -P /lib/ https://github.com/pyroscope-io/pyroscope-dotnet/releases/download/v0.7.0/Pyroscope.Linux.ApiWrapper.x64.so
RUN wget -P /lib/ https://github.com/pyroscope-io/pyroscope-dotnet/releases/download/v0.7.0/Pyroscope.Profiler.Native.so
ENV PYROSCOPE_APPLICATION_NAME=test.dotnet.app
ENV PYROSCOPE_SERVER_ADDRESS=http://pyroscope-route:80
ENV PYROSCOPE_PROFILING_ENABLED=1
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}
ENV CORECLR_PROFILER_PATH=/lib/Pyroscope.Profiler.Native.so
ENV LD_PRELOAD=/lib/Pyroscope.Linux.ApiWrapper.x64.so

ENTRYPOINT ["dotnet", "TestApp.Api.dll"]
```

**Comment by korniltsev** [comment]
I believe we will need to build separate binaries for alpine/musl

**Comment by sentient-glare** [comment]
Gotcha - using Alpine isn't a requirement for me but I got similar results with Debian and Ubuntu

**Comment by korniltsev** [comment]
oops. I will look into it.

**Comment by korniltsev** [comment]
@sentient-glare I tried to reproduce the crash on glibc based base image and could not reproduce

Here is what I tried:
https://github.com/pyroscope-io/pyroscope/blob/fix/crash_dotnet_example/examples/dotnet/web-new/Dockerfile

I wonder what is the difference with your setup on debian base image.
Is there any chance you could share a stacktrace of segmentation fault? or even better a coredump? or even better full self-contained example crashing(not alpine)?

Btw, what is your host OS and architecture?

**Comment by sentient-glare** [comment]
Sorry for the wait on this. I tried out a Dockerfile similar to yours and it worked fine for me, I think I didn't track my local testing all that well and it was using Alpine images that was the issue all along and/or was doing some funky stuff with the libraries 😢 the debian images all work for me now. thanks for the help!
