### ISSUE TITLE
When will upgrade to support .net7 and Live heap profiling?

### ISSUE THREAD

**Issue by unfish** [pyroscope-io/pyroscope-dotnet#22]
The datadog .NET Profiler is already supported this.

**Comment by korniltsev** [comment]
Yeah, we need to merge upstream. I will do it in a couple of weeks

**Comment by korniltsev** [comment]
Please give a try
https://github.com/pyroscope-io/pyroscope-dotnet/releases/tag/v0.8.0-pyroscope
